import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  buildTokens,
  themes,
} from '@karotto/core/theme/themes';
import type { ThemeVariant } from '@karotto/core/theme/themes';

/** Emits every theme's tokens as Kotlin so the Android app renders the same palettes. */
function kotlinMap(
  variant: ThemeVariant | undefined,
  mode: 'light' | 'dark',
): string {
  if (!variant) {
    return 'null';
  }
  const entries = Object.entries(buildTokens(
    variant,
    mode,
  )).map(([
    key,
    value,
  ]) => `            "${key}" to 0xFF${value.slice(1).toUpperCase()}`);
  return `mapOf(\n${entries.join(',\n')},\n        )`;
}

const definitions = themes.map((theme) => `        ThemeDefinition(
            id = "${theme.id}",
            name = "${theme.name.replace(
              /'/g,
              '\\\'',
            )}",
            light = ${kotlinMap(
              theme.light,
              'light',
            )},
            dark = ${kotlinMap(
              theme.dark,
              'dark',
            )},
        )`);

const kotlin = `// Generated by packages/core/scripts/android-themes.ts. Do not edit; run npm run themes:android.
package com.karotto.app.ui.theme

object GeneratedThemes {
    val all: List<ThemeDefinition> = listOf(
${definitions.join(',\n')},
    )
}
`;
const target = resolve(
  import.meta.dirname,
  '../../android/app/src/main/java/com/karotto/app/ui/theme/GeneratedThemes.kt',
);
writeFileSync(
  target,
  kotlin,
);
console.log(`wrote ${target}`);
