import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  defaultThemeId,
  findTheme,
  resolveTheme,
} from '@karotto/core';

/** Emits the default theme as Tailwind theme variables so the first paint needs no JavaScript. */
const { tokens } = resolveTheme(
  findTheme(defaultThemeId),
  'light',
);
const lines = Object.entries(tokens).map(([
  key,
  value,
]) => `  --color-${key}: ${value};`);
const css = `/* Generated by scripts/theme-css.ts from the "${defaultThemeId}" theme. Do not edit. */
@theme {
  --color-*: initial;
  --color-white: #ffffff;
  --color-black: #1a181d;
  --color-transparent: transparent;
  --color-current: currentColor;
${lines.join('\n')}
}
`;
const target = resolve(
  import.meta.dirname,
  '../src/theme.generated.css',
);
writeFileSync(
  target,
  css,
);
console.log(`wrote ${target}`);
